services:
  celestia-validator:
    image: validator
    hostname: validator
    build:
      context: ./celestia
      dockerfile: Dockerfile.validator
    healthcheck:
      # To see health check output:
      # docker inspect --format "{{json .State.Health }}" docker-validator-1 | jq
      test: ["CMD", "/opt/validator-healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 10s
    # uncomment to provide amount of celestia nodes to provision (default: 1)
    # command: [ "/opt/entrypoint.sh", "2" ]
    volumes:
      - type: bind
        source: ./credentials
        target: /credentials
      - genesis:/genesis

  celestia-node-0:
    image: bridge
    build:
      context: ./celestia
      dockerfile: Dockerfile.bridge
    depends_on:
      - celestia-validator
    healthcheck:
      # To see health check output:
      # docker inspect --format "{{json .State.Health }}"  integrations-celestia-node-0-1 | jq
      test: ["CMD", "/opt/bridge-healthcheck.sh", "/credentials/bridge-0.jwt"]
      interval: 5s
      timeout: 5s
      retries: 60
      start_period: 10s
    # uncomment to provide the id of the celestia node (default: 0)
    # command: ["/opt/entrypoint.sh", "0"]
    ports:
      - "127.0.0.1:${CELESTIA_PORT:-26658}:26658"
    volumes:
      - type: bind
        source: ./credentials
        target: /credentials
        consistency: consistent
      - genesis:/genesis
  #  #   Uncomment for another celestia node
  #  #   remember to adjust services.validator.command
  #  celestia-node-1:
  #    image: bridge
  #    build:
  #      context: .
  #      dockerfile: Dockerfile.bridge
  #    depends_on:
  #      - validator
  #    healthcheck:
  #      test: [ "CMD", "/opt/bridge-healthcheck.sh", "/credentials/bridge-1.jwt" ]
  #      interval: 10s
  #      timeout: 5s
  #      retries: 30
  #      start_period: 10s
  #    # The first argument is the id of the celestia node (default: 0)
  #    command: [ "/opt/entrypoint.sh", "1" ]
  #    ports:
  #      # remap the default port as it's already used
  #      - 127.0.0.1:${CELESTIA_PORT_1:-36658}:26658
  #    volumes:
  #      - credentials:/credentials:consistent
  #      - genesis:/genesis

volumes:
  # a temporary fs where the genesis hash is announced
  genesis:
    driver_opts:
      type: tmpfs
      device: tmpfs
